export {default as Home} from './home/Home'
export {default as Theory} from './theory/Theory'
export {default as Practice} from './practice/Practice'
export {default as Login} from './login/Login'
export {default as SignUp} from './signup/SignUp'
